%YAML 1.1
---
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
  build:
    commands:
      - aws s3 sync ./ $S3_BUCKET
      - zip dnd-mapper.zip dnd-mapper.py
      - aws update-function-code --function-name dnd-mapper --zip-file fileb://dnd-mapper.zip  # yamllint disable-line rule:line-length
